import React, { useState } from 'react';
import {
  Flame,
  Clock,
  Calendar,
  BookOpen,
  Play,
  CheckCircle2,
  AlertTriangle,
  ChevronRight,
  Sparkles,
  Zap,
  Target,
  FileText,
} from 'lucide-react';
import { ExamInfo, SubjectData } from '../types';
import { generateEmergencyExamPlan } from '../utils/academicEngine';

interface ExamSurvivalModeProps {
  exams: ExamInfo[];
  subjects: SubjectData[];
  isExamModeActive: boolean;
  onToggleExamMode: () => void;
  onStartFocus: (taskTitle: string) => void;
  darkMode: boolean;
}

export const ExamSurvivalMode: React.FC<ExamSurvivalModeProps> = ({
  exams,
  subjects,
  isExamModeActive,
  onToggleExamMode,
  onStartFocus,
  darkMode,
}) => {
  const [selectedExamId, setSelectedExamId] = useState<string>(exams[0].id);
  const [activeDay, setActiveDay] = useState<number>(1);

  const selectedExam = exams.find((e) => e.id === selectedExamId) || exams[0];
  const emergencyPlan = generateEmergencyExamPlan(selectedExam.daysRemaining, subjects);

  return (
    <div id="exam-survival-mode-view" className="space-y-6 animate-in fade-in duration-300">
      {/* Top Banner with Activation Toggle & Live Countdown */}
      <div
        id="exam-survival-hero"
        className={`p-6 rounded-2xl border transition-all relative overflow-hidden ${
          isExamModeActive
            ? 'bg-gradient-to-br from-rose-950/40 via-slate-900 to-orange-950/40 border-rose-500/40 shadow-lg shadow-rose-950/20'
            : darkMode
            ? 'bg-slate-800/80 border-slate-700'
            : 'bg-white border-slate-200 shadow-xs'
        }`}
      >
        <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-6 relative z-10">
          <div>
            <div className="flex items-center gap-2 mb-1.5">
              <span className="flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-bold bg-rose-500/20 text-rose-500 border border-rose-500/30">
                <Flame className="w-3.5 h-3.5 animate-bounce" />
                AI Exam Survival Mode
              </span>
              <span className="text-xs text-slate-400">• Mid-Term Emergency Plan</span>
            </div>

            <h1 className="text-2xl sm:text-3xl font-black tracking-tight text-slate-900 dark:text-white">
              {selectedExam.subject} Mid-Term 1
            </h1>

            <p className="text-xs sm:text-sm text-slate-600 dark:text-slate-300 max-w-xl mt-1">
              Personalized emergency study plan generated by analyzing your internal marks (41/50), weak topics (AVL Tree rotations), and remaining preparation time.
            </p>

            {/* Countdown Badge */}
            <div className="mt-4 inline-flex items-center gap-3 p-3 rounded-xl bg-rose-500/10 border border-rose-500/20 text-rose-600 dark:text-rose-400">
              <Clock className="w-5 h-5 animate-pulse" />
              <div>
                <p className="text-[10px] uppercase font-bold text-slate-400">Time Until Exam</p>
                <p className="text-xl font-black font-mono tracking-tight leading-none mt-0.5">
                  {selectedExam.daysRemaining} days 12 hours
                </p>
              </div>
              <div className="border-l border-rose-500/20 pl-3">
                <p className="text-[10px] uppercase font-bold text-slate-400">Venue & Time</p>
                <p className="text-xs font-semibold text-slate-700 dark:text-slate-300">
                  {selectedExam.time} • {selectedExam.venue}
                </p>
              </div>
            </div>
          </div>

          {/* Toggle Switch */}
          <div className="flex flex-col sm:flex-row lg:flex-col items-start lg:items-end gap-3">
            <div className="text-right">
              <p className="text-xs font-bold text-slate-900 dark:text-white">
                {isExamModeActive ? 'Survival Mode Active' : 'Survival Mode Standby'}
              </p>
              <p className="text-[11px] text-slate-500">
                {isExamModeActive ? 'Priority study schedules activated' : 'Click to lock in emergency schedule'}
              </p>
            </div>

            <button
              id="toggle-exam-mode-btn"
              onClick={onToggleExamMode}
              className={`px-5 py-2.5 rounded-xl text-xs font-bold tracking-wide transition-all shadow-md active:scale-95 flex items-center gap-2 ${
                isExamModeActive
                  ? 'bg-rose-600 text-white hover:bg-rose-700'
                  : 'bg-gradient-to-r from-indigo-600 to-blue-600 text-white hover:opacity-95'
              }`}
            >
              <Zap className="w-4 h-4 fill-current" />
              <span>{isExamModeActive ? 'Deactivate Exam Mode' : 'Activate Exam Survival Mode'}</span>
            </button>
          </div>
        </div>
      </div>

      {/* Select Exam Tabs */}
      <div className="flex items-center gap-2 overflow-x-auto pb-2 scrollbar-none">
        {exams.map((e) => (
          <button
            key={e.id}
            id={`exam-tab-${e.id}`}
            onClick={() => setSelectedExamId(e.id)}
            className={`shrink-0 flex items-center gap-2 px-3.5 py-2 rounded-xl text-xs font-semibold border transition-all ${
              selectedExam.id === e.id
                ? 'bg-rose-600 text-white border-rose-600 shadow-sm'
                : darkMode
                ? 'bg-slate-800 border-slate-700 text-slate-300'
                : 'bg-white border-slate-200 text-slate-700'
            }`}
          >
            <Calendar className="w-3.5 h-3.5" />
            <span>{e.subject}</span>
            <span className="text-[10px] font-mono px-1.5 py-0.5 rounded bg-white/20 text-white font-bold">
              {e.daysRemaining}d
            </span>
          </button>
        ))}
      </div>

      {/* Emergency Day-by-Day Revision Plan */}
      <div className="space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
          <div>
            <h2 className="text-lg font-bold text-slate-900 dark:text-white tracking-tight flex items-center gap-2">
              <BookOpen className="w-5 h-5 text-indigo-500" />
              Emergency 5-Day Study Schedule
            </h2>
            <p className="text-xs text-slate-500 dark:text-slate-400">
              Balanced for high-yield topic coverage with built-in mock exam practice.
            </p>
          </div>

          {/* Day selection tabs */}
          <div className="flex items-center gap-1 bg-slate-100 dark:bg-slate-800 p-1 rounded-xl">
            {emergencyPlan.map((dayItem) => (
              <button
                key={dayItem.day}
                id={`exam-day-tab-${dayItem.day}`}
                onClick={() => setActiveDay(dayItem.day)}
                className={`px-3 py-1 text-xs font-bold rounded-lg transition-all ${
                  activeDay === dayItem.day
                    ? 'bg-indigo-600 text-white shadow-xs'
                    : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200'
                }`}
              >
                Day {dayItem.day}
              </button>
            ))}
          </div>
        </div>

        {/* Active Day Detail Card */}
        {(() => {
          const currentDayPlan = emergencyPlan.find((p) => p.day === activeDay) || emergencyPlan[0];

          return (
            <div
              id={`day-${activeDay}-plan-card`}
              className={`p-6 rounded-2xl border transition-all ${
                darkMode ? 'bg-slate-800/80 border-slate-700' : 'bg-white border-slate-200 shadow-xs'
              }`}
            >
              <div className="pb-4 mb-4 border-b border-slate-200 dark:border-slate-700 flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                <div>
                  <h3 className="text-base font-extrabold text-slate-900 dark:text-white">
                    {currentDayPlan.title}
                  </h3>
                  <p className="text-xs text-indigo-600 dark:text-indigo-400 font-medium mt-0.5">
                    {currentDayPlan.focusTheme}
                  </p>
                </div>

                <span className="text-xs font-semibold px-2.5 py-1 rounded-md bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border border-indigo-500/20">
                  {currentDayPlan.sessions.length} Targeted Study Blocks
                </span>
              </div>

              {/* Sessions list */}
              <div className="space-y-3">
                {currentDayPlan.sessions.map((session, idx) => (
                  <div
                    key={idx}
                    className={`p-4 rounded-xl border flex flex-col sm:flex-row sm:items-center justify-between gap-4 transition-all ${
                      session.priority === 'critical'
                        ? darkMode
                          ? 'bg-rose-950/20 border-rose-900/40'
                          : 'bg-rose-50/50 border-rose-200'
                        : darkMode
                        ? 'bg-slate-900/60 border-slate-800'
                        : 'bg-slate-50 border-slate-200'
                    }`}
                  >
                    <div className="space-y-1">
                      <div className="flex items-center gap-2">
                        <span className="text-xs font-mono font-bold text-slate-400">
                          {session.time}
                        </span>
                        <span className="px-2 py-0.5 rounded text-[10px] font-bold uppercase bg-slate-200 dark:bg-slate-800 text-slate-700 dark:text-slate-300">
                          {session.subject}
                        </span>
                        {session.priority === 'critical' && (
                          <span className="px-2 py-0.5 rounded text-[10px] font-bold uppercase bg-rose-500/10 text-rose-600 dark:text-rose-400 border border-rose-500/20">
                            Critical Topic
                          </span>
                        )}
                      </div>

                      <h4 className="text-sm font-bold text-slate-900 dark:text-white">
                        {session.topic}
                      </h4>
                      <p className="text-[11px] text-slate-500">
                        Estimated focused duration: <strong>{session.durationMinutes} minutes</strong>
                      </p>
                    </div>

                    <button
                      id={`start-revision-btn-${idx}`}
                      onClick={() => onStartFocus(`${session.subject}: ${session.topic}`)}
                      className="shrink-0 flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-indigo-600 hover:bg-indigo-700 text-white shadow-xs transition-all active:scale-95"
                    >
                      <Play className="w-3 h-3 fill-current" />
                      <span>Start Focus Block</span>
                    </button>
                  </div>
                ))}
              </div>
            </div>
          );
        })()}
      </div>

      {/* Key High-Yield Topics & Revision Flashcards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        <div
          className={`p-5 rounded-2xl border ${
            darkMode ? 'bg-slate-800/80 border-slate-700' : 'bg-white border-slate-200'
          }`}
        >
          <h3 className="text-sm font-bold text-slate-900 dark:text-white flex items-center gap-2 mb-3">
            <Target className="w-4 h-4 text-rose-500" />
            High-Yield Exam Topics (Data Structures)
          </h3>

          <ul className="space-y-2 text-xs">
            {selectedExam.keyTopics.map((topic, i) => (
              <li
                key={i}
                className="p-2.5 rounded-lg bg-slate-100 dark:bg-slate-900/60 flex items-center justify-between"
              >
                <span className="font-semibold text-slate-800 dark:text-slate-200">{topic}</span>
                <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-indigo-500/10 text-indigo-600 dark:text-indigo-400">
                  {i === 0 ? 'Highest Weight (30%)' : i === 1 ? 'High Weight (25%)' : 'Core Module'}
                </span>
              </li>
            ))}
          </ul>
        </div>

        <div
          className={`p-5 rounded-2xl border ${
            darkMode ? 'bg-slate-800/80 border-slate-700' : 'bg-white border-slate-200'
          }`}
        >
          <h3 className="text-sm font-bold text-slate-900 dark:text-white flex items-center gap-2 mb-3">
            <FileText className="w-4 h-4 text-indigo-500" />
            Exam Hall Checklist & Rules
          </h3>

          <div className="space-y-2 text-xs text-slate-600 dark:text-slate-300">
            <p className="flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0" />
              <span>Hall Ticket generated (requires minimum 75% attendance clearance).</span>
            </p>
            <p className="flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0" />
              <span>Physical College ID card mandatory for entry into Exam Hall 3.</span>
            </p>
            <p className="flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0" />
              <span>Non-programmable scientific calculator permitted for Mathematics & Physics.</span>
            </p>
            <p className="flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 text-amber-500 shrink-0" />
              <span>Mobile phones and smart watches strictly prohibited. Report 20 mins early.</span>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
